language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - 'bundle exec rake test'

notifications:
  email: false

# whitelist
branches:
  only:
    - gh-pages
