markdown: kramdown
permalink: /blog/:year/:title/

layouts: ./_noitadnouf

noitadnouf:
  title: Noitad Nouf
  repository: https://github.com/penibelst/jekyll-noitadnouf
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
